version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: crypto-market
    restart: always
    environment:
      POSTGRES_DB: crypto-market-DB
      POSTGRES_USER: alpin3k
      POSTGRES_PASSWORD: alpin3k
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
